import React from 'react'
import Head from 'next/head'
import styles from "../styles/page.module.css"
import { useState } from 'react'

export default function Home() {

  // state ubah background color hitam
  const [dark, setDark] = useState(false);

  // menghandle button dark
  const handleDark = () => {
    setDark(!dark)
  }


  return (
    <div className={`${styles.container_center} ${dark ? styles.container_dark : styles.container_light}`}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Halaman Home</h1>

      <button onClick={handleDark}>Dark / Light</button>

    </div>
  )
}
